import Link from "next/link";

import AppShell from "@/components/layout/AppShell";
import PrototypeField from "@/components/forms/PrototypeField";
import PrototypeNotice from "@/components/prototype/PrototypeNotice";

export default function ProjectNewPage() {
  return (
    <AppShell activeHref="/projects" eyebrow="Projects · New brief" title="Create a project" description="Give a good idea enough shape for the right people to find and join it." actions={<Link className="button-secondary" href="/projects">Cancel</Link>}>
      <PrototypeNotice />
      <div className="editor-layout"><section className="surface-card editor-card" aria-labelledby="project-form-title"><div className="card-heading"><div><span className="panel-kicker">Project brief</span><h2 id="project-form-title">Start with the why.</h2></div><span className="badge">Draft</span></div><form className="prototype-form"><PrototypeField id="project-name" label="Project name" hint="Use a name people can remember and search for." placeholder="e.g. A more welcoming club website" required /><div className="form-grid-two"><div className="field-group"><label className="field-label" htmlFor="project-sig">SIG<span aria-hidden="true">*</span></label><select id="project-sig" defaultValue="web"><option value="web">Web Development</option><option value="ai">Artificial Intelligence</option><option value="design">Design & Media</option><option value="ops">Club operations</option></select><span className="field-hint">This sets the initial project home.</span></div><div className="field-group"><label className="field-label" htmlFor="project-stage">Stage</label><select id="project-stage" defaultValue="exploring"><option value="exploring">Exploring</option><option value="active">In progress</option></select><span className="field-hint">You can change this as the idea takes shape.</span></div></div><div className="field-group"><label className="field-label" htmlFor="project-problem">What are you trying to change?<span aria-hidden="true">*</span></label><textarea id="project-problem" rows={5} placeholder="Describe the problem or opportunity..." required /><span className="field-hint">This is the first thing potential collaborators need to understand.</span></div><div className="field-group"><label className="field-label" htmlFor="project-outcome">What could success look like?</label><textarea id="project-outcome" rows={4} placeholder="Name the smallest useful outcome..." /><span className="field-hint">Keep the first outcome specific and learnable.</span></div><div className="form-actions"><button className="button" type="button">Save project draft</button><button className="button-secondary" type="button">Save and invite collaborators</button></div></form></section><aside className="surface-card editor-aside"><span className="panel-kicker">Good project briefs</span><h2>Invite the next person in.</h2><ul className="simple-list"><li><strong>Make the problem concrete</strong><span>People join problems they can understand.</span></li><li><strong>Name the first milestone</strong><span>A small next step makes joining feel safe.</span></li><li><strong>Leave room to learn</strong><span>The brief is a starting point, not a promise.</span></li></ul><div className="success-state"><strong>Draft saved</strong><span>Just now · visible to you and SIG leads</span></div></aside></div>
    </AppShell>
  );
}
