import Link from "next/link";

import AppShell from "@/components/layout/AppShell";
import PrototypeNotice from "@/components/prototype/PrototypeNotice";

export default function AdminPage() {
  return (
    <AppShell activeHref="/admin" eyebrow="Administration · Overview" title="Keep the club healthy." description="A high-trust view of membership, content, and operational work that needs attention.">
      <PrototypeNotice />
      <div className="content-stat-grid"><section className="surface-card"><span className="panel-kicker">Members</span><strong className="content-stat">184 active</strong><Link className="field-hint text-link" href="/admin/members">Manage members →</Link></section><section className="surface-card"><span className="panel-kicker">Content queue</span><strong className="content-stat">06 waiting</strong><Link className="field-hint text-link" href="/documentation/review">Review documents →</Link></section><section className="surface-card"><span className="panel-kicker">SIGs</span><strong className="content-stat">08 healthy</strong><Link className="field-hint text-link" href="/admin/sigs">Manage SIGs →</Link></section></div>
      <div className="content-two-column admin-two-column"><section className="surface-card content-row-panel" aria-labelledby="admin-actions-title"><div className="card-heading"><div><span className="panel-kicker">Needs attention</span><h2 id="admin-actions-title">Keep the queue moving.</h2></div><span className="badge">04 open</span></div><Link className="content-row" href="/admin/members"><span className="content-row-main"><span className="content-row-category">Membership</span><strong>Review 3 pending member profiles</strong><span>New members · submitted this week</span></span><span className="content-row-arrow" aria-hidden="true">↗</span></Link><Link className="content-row" href="/documentation/review"><span className="content-row-main"><span className="content-row-category">Editorial</span><strong>Review 2 documents</strong><span>Web Development SIG · waiting today</span></span><span className="content-row-arrow" aria-hidden="true">↗</span></Link><Link className="content-row" href="/admin/accounts"><span className="content-row-main"><span className="content-row-category">Accounts</span><strong>Confirm 1 role change</strong><span>Account access · requested yesterday</span></span><span className="content-row-arrow" aria-hidden="true">↗</span></Link></section><section className="surface-card admin-health"><span className="panel-kicker">System signal</span><h2>Quietly in order.</h2><div className="health-list"><span><i className="status-dot" />API connection <strong>Ready</strong></span><span><i className="status-dot" />Content freshness <strong>92%</strong></span><span><i className="status-dot" />Pending permissions <strong>01</strong></span></div></section></div>
      <section className="surface-card forbidden-panel"><span className="panel-kicker">Permission boundary</span><h2>Some controls belong to fewer people.</h2><p>This preview shows the boundary for members without admin access. Production should explain why access is unavailable and where to ask for help.</p><Link className="text-link" href="/dashboard">Return to workspace →</Link></section>
    </AppShell>
  );
}
